version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    volumes: 
      - .:/app/
    # ports:
    #   - "8000:8000"
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./db/data/:/var/lib/mysql 